### ISSUE TITLE
3. Given an author.

### ISSUE THREAD

**Issue by DanielHauge** [soft2018spring-gruppe10/Backend#1]
I was thinking, if we could change the api protol from 
```
/api/books/byauthor/{authorId}
```
to 
```
/api/books/byauthor/{authorName}
```
As to just working with strings instead of ID. Reasoning is, we have to refractor the data structure if we want to have unique author id's. Furthermore it is quite easy to work with author as a string istead, also for the key value store. But let me know what you guys think.

**Comment by edipetres** [comment]
Let's go with the author name then!
